export const VALUE_DATE_FORMAT = 'YYYY-MM-DD';
export const DATE_DISPLAY_FORMAT = 'MMMM D, YYYY';
export const TIME_FORMAT = 'HH:mm';
export const DATE_PICKER_FORMAT = 'DD MMM YYYY';
export const DATE_TIME_PICKER_FORMAT = 'DD MMM YYYY HH:mm';
export const DATE_TIME_FORMAT = 'YYYY-MM-DDTHH:mm:ss';
export const CALENDAR_DATE_FORMAT = 'MMMM YYYY';
export const LONG_DATE_FORMAT = 'dddd, D MMMM YYYY';
export const LONG_DATE_TIME_FORMAT = 'dddd, D MMMM YYYY HH:mm';

export default {
  VALUE_DATE_FORMAT,
  DATE_DISPLAY_FORMAT,
  TIME_FORMAT,
  DATE_PICKER_FORMAT,
  DATE_TIME_FORMAT,
  DATE_TIME_PICKER_FORMAT,
  CALENDAR_DATE_FORMAT,
  LONG_DATE_FORMAT,
  LONG_DATE_TIME_FORMAT,
};
