/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersPublicController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/users/{id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersPublicController_findAllServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/update-avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_updateUserAvatar"];
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ServicesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/combination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ServicesController_createCombination"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/combination/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ServicesController_updateCombinationById"];
        post?: never;
        delete: operations["ServicesController_deleteCombinationById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ServicesController_updateById"];
        post?: never;
        delete: operations["ServicesController_deleteById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ServicesPublicController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/services/combination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ServicesPublicController_findCombination"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ServicesPublicController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/masters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MastersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/masters/{id}/combinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MastersController_findAllCombinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/masters/{id}/update-avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["MastersController_updateUserAvatar"];
        trace?: never;
    };
    "/public/masters/{id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MastersPublicController_findAllServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesPublicController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesPublicController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponseDto: {
            /** @example success */
            status: string;
            data: Record<string, never>;
        };
        UserEntity: {
            id: number;
            name: string | null;
            email: string;
            avatarUrl: string | null;
            avatarPreviewUrl: string | null;
            phone: string | null;
        };
        UserResponseDto: {
            token: string;
            user: components["schemas"]["UserEntity"];
        };
        PaginationDto: {
            /** @example 100 */
            total: number;
            /** @example 1 */
            currentPage: number;
            /** @example 10 */
            totalPages: number;
            /** @example 10 */
            perPage: number;
        };
        LoginRequestDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        ErrorItemDto: {
            /** @example email */
            field: string;
            /** @example Email is not valid */
            message: string;
        };
        ErrorResponseDto: {
            /** @example error */
            status: string;
            /** @example Bad request */
            errorMessage: string;
            /** @example null */
            data: Record<string, never> | null;
            /** @example [] */
            errors?: components["schemas"]["ErrorItemDto"][];
        };
        CreateUserDto: {
            /**
             * @description User name (optional)
             * @example My name
             */
            name?: Record<string, never>;
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
        };
        CategoryEntity: {
            id: number;
            name: string;
            description: string;
            image_url: string;
        };
        MasterEntity: {
            id: number;
            name: string | null;
            email: string;
            avatarUrl: string | null;
            avatarPreviewUrl: string | null;
            phone: string | null;
        };
        ServiceEntity: {
            id: number;
            name: string;
            description: string;
            price: number;
            priceCurrency: string;
            category: components["schemas"]["CategoryEntity"];
            durationMinutes: number;
            isActive: boolean;
            masters: components["schemas"]["MasterEntity"][];
            user: components["schemas"]["UserEntity"];
        };
        UpdateUserAvatarResponseDto: {
            user: components["schemas"]["UserEntity"];
        };
        UpdateUserAvatarDto: {
            /** Format: binary */
            file: string;
        };
        CreateServiceDto: {
            /**
             * @description Name of the service
             * @example Haircut
             */
            name: string;
            /**
             * @description Description of the service
             * @example A stylish haircut for men
             */
            description: string;
            /**
             * @description Price of the service
             * @example 25.5
             */
            price: number;
            /**
             * @description Currency of the service price
             * @example EUR
             */
            priceCurrency: string;
            /**
             * @description ID of the category the service belongs to
             * @example 1
             */
            categoryId: number;
            /**
             * @description Duration of the service in minutes
             * @example 60
             */
            durationMinutes: number;
            /**
             * @description Is the service active
             * @default true
             */
            isActive: boolean;
            /**
             * @description List of master IDs who can perform this service
             * @example [
             *       1
             *     ]
             */
            masterIds?: string[];
        };
        CombinationEntity: {
            id: number;
            name: string;
            durationMinutes: number;
            services: components["schemas"]["ServiceEntity"];
        };
        CreateCombinationDto: {
            /**
             * @description Name of the service combination
             * @example Relaxing Massage Combo
             */
            name: string;
            /**
             * @description Duration of the combination in minutes
             * @example 90
             */
            durationMinutes: number;
            /**
             * @description Array of service IDs included in the combination
             * @example [
             *       1,
             *       2
             *     ]
             */
            serviceIds: string[];
        };
        UpdateCombinationDto: {
            /**
             * @description Name of the service combination
             * @example Relaxing Spa Package
             */
            name: string;
            /**
             * @description Duration of the combination in minutes
             * @example 75
             */
            durationMinutes: number;
            /**
             * @description Array of service IDs included in the combination
             * @example [
             *       1,
             *       3
             *     ]
             */
            serviceIds: string[];
        };
        UpdateServiceDto: {
            /**
             * @description Name of the service
             * @example Haircut
             */
            name: string;
            /**
             * @description Description of the service
             * @example A stylish haircut for men
             */
            description: string;
            /**
             * @description Price of the service
             * @example 25.5
             */
            price: number;
            /**
             * @description Currency of the service price
             * @example EUR
             */
            priceCurrency: string;
            /**
             * @description ID of the category the service belongs to
             * @example 1
             */
            categoryId: number;
            /**
             * @description Duration of the service in minutes
             * @example 60
             */
            durationMinutes: number;
            /**
             * @description Is the service active
             * @default true
             */
            isActive: boolean;
            /**
             * @description List of master IDs who can perform this service
             * @example [
             *       1
             *     ]
             */
            masterIds?: string[];
        };
        UpdateMasterAvatarResponseDto: {
            master: components["schemas"]["MasterEntity"];
        };
        UpdateMasterAvatarDto: {
            /** Format: binary */
            file: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDto"];
            };
        };
        responses: {
            /** @description User logged in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["UserResponseDto"];
                    };
                };
            };
            /** @description Invalid credentials */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["UserResponseDto"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        /** @example {} */
                        data?: Record<string, never>;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersPublicController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: {
                            items?: components["schemas"]["UserEntity"][];
                            pagination?: components["schemas"]["PaginationDto"];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersPublicController_findAllServices: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
                /** @description Filter by category ID */
                categoryId?: number;
                /** @description Minimum price */
                minPrice?: number;
                /** @description Maximum price */
                maxPrice?: number;
                /** @description Search keyword (in name, description, user name, or master name) */
                search?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all user's services */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: {
                            items?: components["schemas"]["ServiceEntity"][];
                            pagination?: components["schemas"]["PaginationDto"];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersController_updateUserAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UpdateUserAvatarDto"];
            };
        };
        responses: {
            /** @description Avatar updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["UpdateUserAvatarResponseDto"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ServicesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceDto"];
            };
        };
        responses: {
            /** @description Service created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["ServiceEntity"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ServicesController_createCombination: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCombinationDto"];
            };
        };
        responses: {
            /** @description Combination created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["CombinationEntity"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ServicesController_updateCombinationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCombinationDto"];
            };
        };
        responses: {
            /** @description Combination updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["CombinationEntity"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ServicesController_deleteCombinationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combination deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["CombinationEntity"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ServicesController_updateById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceDto"];
            };
        };
        responses: {
            /** @description Service updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["ServiceEntity"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ServicesController_deleteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["ServiceEntity"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ServicesPublicController_findAll: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
                /** @description Filter by category ID */
                categoryId?: number;
                /** @description Minimum price */
                minPrice?: number;
                /** @description Maximum price */
                maxPrice?: number;
                /** @description Search keyword (in name, description, user name, or master name) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all services */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: {
                            items?: components["schemas"]["ServiceEntity"][];
                            pagination?: components["schemas"]["PaginationDto"];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ServicesPublicController_findCombination: {
        parameters: {
            query: {
                services: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combination found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["CombinationEntity"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ServicesPublicController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["ServiceEntity"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    MastersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of masters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: {
                            items?: components["schemas"]["MasterEntity"][];
                            pagination?: components["schemas"]["PaginationDto"];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    MastersController_findAllCombinations: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
                /** @description Search keyword to filter combinations by name */
                search?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of master's combinations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: {
                            items?: components["schemas"]["CombinationEntity"][];
                            pagination?: components["schemas"]["PaginationDto"];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    MastersController_updateUserAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UpdateMasterAvatarDto"];
            };
        };
        responses: {
            /** @description Avatar updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["UpdateMasterAvatarResponseDto"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    MastersPublicController_findAllServices: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
                /** @description Filter by category ID */
                categoryId?: number;
                /** @description Minimum price */
                minPrice?: number;
                /** @description Maximum price */
                maxPrice?: number;
                /** @description Search keyword (in name, description, user name, or master name) */
                search?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all master's services */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: {
                            items?: components["schemas"]["ServiceEntity"][];
                            pagination?: components["schemas"]["PaginationDto"];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoriesPublicController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: {
                            items?: components["schemas"]["CategoryEntity"][];
                            pagination?: components["schemas"]["PaginationDto"];
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoriesPublicController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"] & {
                        data?: components["schemas"]["CategoryEntity"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
