export const VALUE_DATE_FORMAT = 'YYYY-MM-DD';
export const DATE_DISPLAY_FORMAT = 'ddd DD MMM YYYY';
export const TIME_FORMAT = 'HH:mm';
export const DATE_PICKER_FORMAT = 'DD MMM YYYY';
export const DATE_TIME_FORMAT = 'YYYY-MM-DDTHH:mm:ss';

export default {
  VALUE_DATE_FORMAT,
  DATE_DISPLAY_FORMAT,
  TIME_FORMAT,
  DATE_PICKER_FORMAT,
  DATE_TIME_FORMAT,
};
