export enum appRoutes {
  Home = '/app',
  SignIn = '/app/sign-in',
  SignUp = '/app/sign-up',
  ForgotPassword = '/app/forgot-password',
  VerifyCode = '/app/verify-code',
  ResetPassword = '/app/reset-password',
  EditProfile = '/app/profile/edit-profile',
  EditLanguages = '/app/profile/edit-languages',
  Masters = '/app/masters',
  AddMaster = '/app/masters/add-master',
  Certificates = '/app/profile/certificates',
  WorkingHours = '/app/profile/working-hours',
  Posts = '/app/profile/posts',
  Gallery = '/app/profile/gallery',
  Calendar = '/app/calendar',
  TimeOff = '/app/time-off',
  AddTimeOff = '/app/time-off/add-time-off',
  Clients = '/app/clients',
  Services = '/app/services',
  AddPost = '/app/add-post',
  Profile = '/app/profile',
  Notifications = '/app/notifications',
  CreateService = '/app/services/create',
  OrderCreate = '/app/orders/create',
}
export enum clientRoutes {
  Home = '/',
}
