#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "$(git rev-parse --show-toplevel)" || exit 1

echo "🔍 Running lint-staged on changed files..."

# Lint only staged files
corepack yarn lint-staged || {
  echo "❌ Lint-staged failed. Commit aborted."
  exit 1
}

echo "🔎 Running next build check..."
corepack yarn build:web || {
  echo "❌ Build failed. Commit aborted."
  exit 1
}

echo "✅ Checks passed. Proceeding with commit..."
