#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "$(git rev-parse --show-toplevel)" || exit 1

echo "🔍 Running full lint before commit..."
corepack yarn lint -- --max-warnings=10 || {
  echo "❌ Lint failed. Commit aborted."
  exit 1
}

echo "✅ Lint passed. Proceeding with commit..."
